/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as PhotosIdRouteImport } from './routes/photos.$id'
import { Route as GalleriesSlugRouteImport } from './routes/galleries.$slug'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as AuthenticatedAdminTypographyRouteImport } from './routes/_authenticated/admin.typography'
import { Route as AuthenticatedAdminTickerRouteImport } from './routes/_authenticated/admin.ticker'
import { Route as AuthenticatedAdminStudioRouteImport } from './routes/_authenticated/admin.studio'
import { Route as AuthenticatedAdminReelsRouteImport } from './routes/_authenticated/admin.reels'
import { Route as AuthenticatedAdminPlacesRouteImport } from './routes/_authenticated/admin.places'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin.inbox'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminGalleriesRouteImport } from './routes/_authenticated/admin.galleries'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminTypographyIndexRouteImport } from './routes/_authenticated/admin.typography.index'
import { Route as AuthenticatedAdminLeadsIndexRouteImport } from './routes/_authenticated/admin.leads.index'
import { Route as AuthenticatedAdminGalleryIndexRouteImport } from './routes/_authenticated/admin.gallery.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminTypographySettingsRouteImport } from './routes/_authenticated/admin.typography.settings'
import { Route as AuthenticatedAdminLeadsIdRouteImport } from './routes/_authenticated/admin.leads.$id'
import { Route as AuthenticatedAdminGalleryIdRouteImport } from './routes/_authenticated/admin.gallery.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhotosRoute,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIdRoute = PhotosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PhotosRoute,
} as any)
const GalleriesSlugRoute = GalleriesSlugRouteImport.update({
  id: '/galleries/$slug',
  path: '/galleries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTypographyRoute =
  AuthenticatedAdminTypographyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTickerRoute =
  AuthenticatedAdminTickerRouteImport.update({
    id: '/ticker',
    path: '/ticker',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudioRoute =
  AuthenticatedAdminStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReelsRoute = AuthenticatedAdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPlacesRoute =
  AuthenticatedAdminPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleriesRoute =
  AuthenticatedAdminGalleriesRouteImport.update({
    id: '/galleries',
    path: '/galleries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTypographyIndexRoute =
  AuthenticatedAdminTypographyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTypographyRoute,
  } as any)
const AuthenticatedAdminLeadsIndexRoute =
  AuthenticatedAdminLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminGalleryIndexRoute =
  AuthenticatedAdminGalleryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminGalleryRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminTypographySettingsRoute =
  AuthenticatedAdminTypographySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminTypographyRoute,
  } as any)
const AuthenticatedAdminLeadsIdRoute =
  AuthenticatedAdminLeadsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminGalleryIdRoute =
  AuthenticatedAdminGalleryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminGalleryRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/photos': typeof PhotosRouteWithChildren
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRouteWithChildren
  '/weather': typeof WeatherRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRouteWithChildren
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/typography': typeof AuthenticatedAdminTypographyRouteWithChildren
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/typography/': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weather': typeof WeatherRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/businesses': typeof BusinessesIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/places': typeof PlacesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/typography': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/photos': typeof PhotosRouteWithChildren
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRouteWithChildren
  '/weather': typeof WeatherRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRouteWithChildren
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/_authenticated/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/_authenticated/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/_authenticated/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/_authenticated/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/_authenticated/admin/typography': typeof AuthenticatedAdminTypographyRouteWithChildren
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/_authenticated/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/_authenticated/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/_authenticated/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/_authenticated/admin/typography/': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/contact'
    | '/photos'
    | '/reels'
    | '/sitemap.xml'
    | '/videos'
    | '/weather'
    | '/admin'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/places/$slug'
    | '/videos/$id'
    | '/businesses/'
    | '/photos/'
    | '/places/'
    | '/videos/'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/events'
    | '/admin/galleries'
    | '/admin/gallery'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/places'
    | '/admin/reels'
    | '/admin/studio'
    | '/admin/ticker'
    | '/admin/typography'
    | '/api/media/$'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/clients/$id'
    | '/admin/gallery/$id'
    | '/admin/leads/$id'
    | '/admin/typography/settings'
    | '/admin/blog/'
    | '/admin/clients/'
    | '/admin/gallery/'
    | '/admin/leads/'
    | '/admin/typography/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/contact'
    | '/reels'
    | '/sitemap.xml'
    | '/weather'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/places/$slug'
    | '/videos/$id'
    | '/businesses'
    | '/photos'
    | '/places'
    | '/videos'
    | '/admin/events'
    | '/admin/galleries'
    | '/admin/inbox'
    | '/admin/places'
    | '/admin/reels'
    | '/admin/studio'
    | '/admin/ticker'
    | '/api/media/$'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/clients/$id'
    | '/admin/gallery/$id'
    | '/admin/leads/$id'
    | '/admin/typography/settings'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/gallery'
    | '/admin/leads'
    | '/admin/typography'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/contact'
    | '/photos'
    | '/reels'
    | '/sitemap.xml'
    | '/videos'
    | '/weather'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/places/$slug'
    | '/videos/$id'
    | '/businesses/'
    | '/photos/'
    | '/places/'
    | '/videos/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/galleries'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/places'
    | '/_authenticated/admin/reels'
    | '/_authenticated/admin/studio'
    | '/_authenticated/admin/ticker'
    | '/_authenticated/admin/typography'
    | '/api/media/$'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/gallery/$id'
    | '/_authenticated/admin/leads/$id'
    | '/_authenticated/admin/typography/settings'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/gallery/'
    | '/_authenticated/admin/leads/'
    | '/_authenticated/admin/typography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  PhotosRoute: typeof PhotosRouteWithChildren
  ReelsRoute: typeof ReelsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRouteWithChildren
  WeatherRoute: typeof WeatherRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  GalleriesSlugRoute: typeof GalleriesSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$id': {
      id: '/photos/$id'
      path: '/$id'
      fullPath: '/photos/$id'
      preLoaderRoute: typeof PhotosIdRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/galleries/$slug': {
      id: '/galleries/$slug'
      path: '/galleries/$slug'
      fullPath: '/galleries/$slug'
      preLoaderRoute: typeof GalleriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/typography': {
      id: '/_authenticated/admin/typography'
      path: '/typography'
      fullPath: '/admin/typography'
      preLoaderRoute: typeof AuthenticatedAdminTypographyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticker': {
      id: '/_authenticated/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AuthenticatedAdminTickerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/studio': {
      id: '/_authenticated/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AuthenticatedAdminStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reels': {
      id: '/_authenticated/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AuthenticatedAdminReelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/places': {
      id: '/_authenticated/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AuthenticatedAdminPlacesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galleries': {
      id: '/_authenticated/admin/galleries'
      path: '/galleries'
      fullPath: '/admin/galleries'
      preLoaderRoute: typeof AuthenticatedAdminGalleriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/typography/': {
      id: '/_authenticated/admin/typography/'
      path: '/'
      fullPath: '/admin/typography/'
      preLoaderRoute: typeof AuthenticatedAdminTypographyIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTypographyRoute
    }
    '/_authenticated/admin/leads/': {
      id: '/_authenticated/admin/leads/'
      path: '/'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/gallery/': {
      id: '/_authenticated/admin/gallery/'
      path: '/'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AuthenticatedAdminGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminGalleryRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/typography/settings': {
      id: '/_authenticated/admin/typography/settings'
      path: '/settings'
      fullPath: '/admin/typography/settings'
      preLoaderRoute: typeof AuthenticatedAdminTypographySettingsRouteImport
      parentRoute: typeof AuthenticatedAdminTypographyRoute
    }
    '/_authenticated/admin/leads/$id': {
      id: '/_authenticated/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/gallery/$id': {
      id: '/_authenticated/admin/gallery/$id'
      path: '/$id'
      fullPath: '/admin/gallery/$id'
      preLoaderRoute: typeof AuthenticatedAdminGalleryIdRouteImport
      parentRoute: typeof AuthenticatedAdminGalleryRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
  }
}

interface AuthenticatedAdminBlogRouteChildren {
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminBlogRouteChildren: AuthenticatedAdminBlogRouteChildren =
  {
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  }

const AuthenticatedAdminBlogRouteWithChildren =
  AuthenticatedAdminBlogRoute._addFileChildren(
    AuthenticatedAdminBlogRouteChildren,
  )

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminGalleryRouteChildren {
  AuthenticatedAdminGalleryIdRoute: typeof AuthenticatedAdminGalleryIdRoute
  AuthenticatedAdminGalleryIndexRoute: typeof AuthenticatedAdminGalleryIndexRoute
}

const AuthenticatedAdminGalleryRouteChildren: AuthenticatedAdminGalleryRouteChildren =
  {
    AuthenticatedAdminGalleryIdRoute: AuthenticatedAdminGalleryIdRoute,
    AuthenticatedAdminGalleryIndexRoute: AuthenticatedAdminGalleryIndexRoute,
  }

const AuthenticatedAdminGalleryRouteWithChildren =
  AuthenticatedAdminGalleryRoute._addFileChildren(
    AuthenticatedAdminGalleryRouteChildren,
  )

interface AuthenticatedAdminLeadsRouteChildren {
  AuthenticatedAdminLeadsIdRoute: typeof AuthenticatedAdminLeadsIdRoute
  AuthenticatedAdminLeadsIndexRoute: typeof AuthenticatedAdminLeadsIndexRoute
}

const AuthenticatedAdminLeadsRouteChildren: AuthenticatedAdminLeadsRouteChildren =
  {
    AuthenticatedAdminLeadsIdRoute: AuthenticatedAdminLeadsIdRoute,
    AuthenticatedAdminLeadsIndexRoute: AuthenticatedAdminLeadsIndexRoute,
  }

const AuthenticatedAdminLeadsRouteWithChildren =
  AuthenticatedAdminLeadsRoute._addFileChildren(
    AuthenticatedAdminLeadsRouteChildren,
  )

interface AuthenticatedAdminTypographyRouteChildren {
  AuthenticatedAdminTypographySettingsRoute: typeof AuthenticatedAdminTypographySettingsRoute
  AuthenticatedAdminTypographyIndexRoute: typeof AuthenticatedAdminTypographyIndexRoute
}

const AuthenticatedAdminTypographyRouteChildren: AuthenticatedAdminTypographyRouteChildren =
  {
    AuthenticatedAdminTypographySettingsRoute:
      AuthenticatedAdminTypographySettingsRoute,
    AuthenticatedAdminTypographyIndexRoute:
      AuthenticatedAdminTypographyIndexRoute,
  }

const AuthenticatedAdminTypographyRouteWithChildren =
  AuthenticatedAdminTypographyRoute._addFileChildren(
    AuthenticatedAdminTypographyRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRouteWithChildren
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminGalleriesRoute: typeof AuthenticatedAdminGalleriesRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRouteWithChildren
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRouteWithChildren
  AuthenticatedAdminPlacesRoute: typeof AuthenticatedAdminPlacesRoute
  AuthenticatedAdminReelsRoute: typeof AuthenticatedAdminReelsRoute
  AuthenticatedAdminStudioRoute: typeof AuthenticatedAdminStudioRoute
  AuthenticatedAdminTickerRoute: typeof AuthenticatedAdminTickerRoute
  AuthenticatedAdminTypographyRoute: typeof AuthenticatedAdminTypographyRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRouteWithChildren,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminGalleriesRoute: AuthenticatedAdminGalleriesRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRouteWithChildren,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRouteWithChildren,
  AuthenticatedAdminPlacesRoute: AuthenticatedAdminPlacesRoute,
  AuthenticatedAdminReelsRoute: AuthenticatedAdminReelsRoute,
  AuthenticatedAdminStudioRoute: AuthenticatedAdminStudioRoute,
  AuthenticatedAdminTickerRoute: AuthenticatedAdminTickerRoute,
  AuthenticatedAdminTypographyRoute:
    AuthenticatedAdminTypographyRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PhotosRouteChildren {
  PhotosIdRoute: typeof PhotosIdRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
}

const PhotosRouteChildren: PhotosRouteChildren = {
  PhotosIdRoute: PhotosIdRoute,
  PhotosIndexRoute: PhotosIndexRoute,
}

const PhotosRouteWithChildren =
  PhotosRoute._addFileChildren(PhotosRouteChildren)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  PhotosRoute: PhotosRouteWithChildren,
  ReelsRoute: ReelsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRouteWithChildren,
  WeatherRoute: WeatherRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  GalleriesSlugRoute: GalleriesSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
