/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as PhotosIdRouteImport } from './routes/photos.$id'
import { Route as GalleriesSlugRouteImport } from './routes/galleries.$slug'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as AuthenticatedAdminTypographyRouteImport } from './routes/_authenticated/admin.typography'
import { Route as AuthenticatedAdminTickerRouteImport } from './routes/_authenticated/admin.ticker'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminStudioRouteImport } from './routes/_authenticated/admin.studio'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminReelsRouteImport } from './routes/_authenticated/admin.reels'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin.portfolio'
import { Route as AuthenticatedAdminPlacesRouteImport } from './routes/_authenticated/admin.places'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin.inbox'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminGalleriesRouteImport } from './routes/_authenticated/admin.galleries'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminTypographyIndexRouteImport } from './routes/_authenticated/admin.typography.index'
import { Route as AuthenticatedAdminTestimonialsIndexRouteImport } from './routes/_authenticated/admin.testimonials.index'
import { Route as AuthenticatedAdminTeamIndexRouteImport } from './routes/_authenticated/admin.team.index'
import { Route as AuthenticatedAdminServicesIndexRouteImport } from './routes/_authenticated/admin.services.index'
import { Route as AuthenticatedAdminPricingIndexRouteImport } from './routes/_authenticated/admin.pricing.index'
import { Route as AuthenticatedAdminPortfolioIndexRouteImport } from './routes/_authenticated/admin.portfolio.index'
import { Route as AuthenticatedAdminLeadsIndexRouteImport } from './routes/_authenticated/admin.leads.index'
import { Route as AuthenticatedAdminGalleryIndexRouteImport } from './routes/_authenticated/admin.gallery.index'
import { Route as AuthenticatedAdminFaqsIndexRouteImport } from './routes/_authenticated/admin.faqs.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminTypographySettingsRouteImport } from './routes/_authenticated/admin.typography.settings'
import { Route as AuthenticatedAdminTestimonialsIdRouteImport } from './routes/_authenticated/admin.testimonials.$id'
import { Route as AuthenticatedAdminTeamIdRouteImport } from './routes/_authenticated/admin.team.$id'
import { Route as AuthenticatedAdminServicesIdRouteImport } from './routes/_authenticated/admin.services.$id'
import { Route as AuthenticatedAdminPricingIdRouteImport } from './routes/_authenticated/admin.pricing.$id'
import { Route as AuthenticatedAdminPortfolioIdRouteImport } from './routes/_authenticated/admin.portfolio.$id'
import { Route as AuthenticatedAdminLeadsIdRouteImport } from './routes/_authenticated/admin.leads.$id'
import { Route as AuthenticatedAdminGalleryIdRouteImport } from './routes/_authenticated/admin.gallery.$id'
import { Route as AuthenticatedAdminFaqsIdRouteImport } from './routes/_authenticated/admin.faqs.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhotosRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const PhotosIdRoute = PhotosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PhotosRoute,
} as any)
const GalleriesSlugRoute = GalleriesSlugRouteImport.update({
  id: '/galleries/$slug',
  path: '/galleries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTypographyRoute =
  AuthenticatedAdminTypographyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTickerRoute =
  AuthenticatedAdminTickerRouteImport.update({
    id: '/ticker',
    path: '/ticker',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStudioRoute =
  AuthenticatedAdminStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReelsRoute = AuthenticatedAdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlacesRoute =
  AuthenticatedAdminPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleriesRoute =
  AuthenticatedAdminGalleriesRouteImport.update({
    id: '/galleries',
    path: '/galleries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTypographyIndexRoute =
  AuthenticatedAdminTypographyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTypographyRoute,
  } as any)
const AuthenticatedAdminTestimonialsIndexRoute =
  AuthenticatedAdminTestimonialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTestimonialsRoute,
  } as any)
const AuthenticatedAdminTeamIndexRoute =
  AuthenticatedAdminTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTeamRoute,
  } as any)
const AuthenticatedAdminServicesIndexRoute =
  AuthenticatedAdminServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminServicesRoute,
  } as any)
const AuthenticatedAdminPricingIndexRoute =
  AuthenticatedAdminPricingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPricingRoute,
  } as any)
const AuthenticatedAdminPortfolioIndexRoute =
  AuthenticatedAdminPortfolioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPortfolioRoute,
  } as any)
const AuthenticatedAdminLeadsIndexRoute =
  AuthenticatedAdminLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminGalleryIndexRoute =
  AuthenticatedAdminGalleryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminGalleryRoute,
  } as any)
const AuthenticatedAdminFaqsIndexRoute =
  AuthenticatedAdminFaqsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminFaqsRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminTypographySettingsRoute =
  AuthenticatedAdminTypographySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminTypographyRoute,
  } as any)
const AuthenticatedAdminTestimonialsIdRoute =
  AuthenticatedAdminTestimonialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTestimonialsRoute,
  } as any)
const AuthenticatedAdminTeamIdRoute =
  AuthenticatedAdminTeamIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTeamRoute,
  } as any)
const AuthenticatedAdminServicesIdRoute =
  AuthenticatedAdminServicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminServicesRoute,
  } as any)
const AuthenticatedAdminPricingIdRoute =
  AuthenticatedAdminPricingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPricingRoute,
  } as any)
const AuthenticatedAdminPortfolioIdRoute =
  AuthenticatedAdminPortfolioIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPortfolioRoute,
  } as any)
const AuthenticatedAdminLeadsIdRoute =
  AuthenticatedAdminLeadsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminGalleryIdRoute =
  AuthenticatedAdminGalleryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminGalleryRoute,
  } as any)
const AuthenticatedAdminFaqsIdRoute =
  AuthenticatedAdminFaqsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminFaqsRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/photos': typeof PhotosRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reels': typeof ReelsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRouteWithChildren
  '/weather': typeof WeatherRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/photos/': typeof PhotosIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRouteWithChildren
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRouteWithChildren
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AuthenticatedAdminPricingRouteWithChildren
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRouteWithChildren
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/team': typeof AuthenticatedAdminTeamRouteWithChildren
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRouteWithChildren
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/typography': typeof AuthenticatedAdminTypographyRouteWithChildren
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/faqs/$id': typeof AuthenticatedAdminFaqsIdRoute
  '/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AuthenticatedAdminPricingIdRoute
  '/admin/services/$id': typeof AuthenticatedAdminServicesIdRoute
  '/admin/team/$id': typeof AuthenticatedAdminTeamIdRoute
  '/admin/testimonials/$id': typeof AuthenticatedAdminTestimonialsIdRoute
  '/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/faqs/': typeof AuthenticatedAdminFaqsIndexRoute
  '/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/portfolio/': typeof AuthenticatedAdminPortfolioIndexRoute
  '/admin/pricing/': typeof AuthenticatedAdminPricingIndexRoute
  '/admin/services/': typeof AuthenticatedAdminServicesIndexRoute
  '/admin/team/': typeof AuthenticatedAdminTeamIndexRoute
  '/admin/testimonials/': typeof AuthenticatedAdminTestimonialsIndexRoute
  '/admin/typography/': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reels': typeof ReelsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weather': typeof WeatherRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/photos': typeof PhotosIndexRoute
  '/services': typeof ServicesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/faqs/$id': typeof AuthenticatedAdminFaqsIdRoute
  '/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AuthenticatedAdminPricingIdRoute
  '/admin/services/$id': typeof AuthenticatedAdminServicesIdRoute
  '/admin/team/$id': typeof AuthenticatedAdminTeamIdRoute
  '/admin/testimonials/$id': typeof AuthenticatedAdminTestimonialsIdRoute
  '/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsIndexRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioIndexRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingIndexRoute
  '/admin/services': typeof AuthenticatedAdminServicesIndexRoute
  '/admin/team': typeof AuthenticatedAdminTeamIndexRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsIndexRoute
  '/admin/typography': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/photos': typeof PhotosRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reels': typeof ReelsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRouteWithChildren
  '/weather': typeof WeatherRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/galleries/$slug': typeof GalleriesSlugRoute
  '/photos/$id': typeof PhotosIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/videos/$id': typeof VideosIdRoute
  '/photos/': typeof PhotosIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRouteWithChildren
  '/_authenticated/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRouteWithChildren
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRouteWithChildren
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRouteWithChildren
  '/_authenticated/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRouteWithChildren
  '/_authenticated/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRouteWithChildren
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRouteWithChildren
  '/_authenticated/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/_authenticated/admin/typography': typeof AuthenticatedAdminTypographyRouteWithChildren
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/faqs/$id': typeof AuthenticatedAdminFaqsIdRoute
  '/_authenticated/admin/gallery/$id': typeof AuthenticatedAdminGalleryIdRoute
  '/_authenticated/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/_authenticated/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/_authenticated/admin/pricing/$id': typeof AuthenticatedAdminPricingIdRoute
  '/_authenticated/admin/services/$id': typeof AuthenticatedAdminServicesIdRoute
  '/_authenticated/admin/team/$id': typeof AuthenticatedAdminTeamIdRoute
  '/_authenticated/admin/testimonials/$id': typeof AuthenticatedAdminTestimonialsIdRoute
  '/_authenticated/admin/typography/settings': typeof AuthenticatedAdminTypographySettingsRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/faqs/': typeof AuthenticatedAdminFaqsIndexRoute
  '/_authenticated/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/_authenticated/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/_authenticated/admin/portfolio/': typeof AuthenticatedAdminPortfolioIndexRoute
  '/_authenticated/admin/pricing/': typeof AuthenticatedAdminPricingIndexRoute
  '/_authenticated/admin/services/': typeof AuthenticatedAdminServicesIndexRoute
  '/_authenticated/admin/team/': typeof AuthenticatedAdminTeamIndexRoute
  '/_authenticated/admin/testimonials/': typeof AuthenticatedAdminTestimonialsIndexRoute
  '/_authenticated/admin/typography/': typeof AuthenticatedAdminTypographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/clients'
    | '/contact'
    | '/faq'
    | '/photos'
    | '/portfolio'
    | '/pricing'
    | '/reels'
    | '/services'
    | '/sitemap.xml'
    | '/videos'
    | '/weather'
    | '/admin'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/videos/$id'
    | '/photos/'
    | '/services/'
    | '/videos/'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/galleries'
    | '/admin/gallery'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/places'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/reels'
    | '/admin/services'
    | '/admin/studio'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/ticker'
    | '/admin/typography'
    | '/api/media/$'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/clients/$id'
    | '/admin/faqs/$id'
    | '/admin/gallery/$id'
    | '/admin/leads/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/team/$id'
    | '/admin/testimonials/$id'
    | '/admin/typography/settings'
    | '/admin/blog/'
    | '/admin/clients/'
    | '/admin/faqs/'
    | '/admin/gallery/'
    | '/admin/leads/'
    | '/admin/portfolio/'
    | '/admin/pricing/'
    | '/admin/services/'
    | '/admin/team/'
    | '/admin/testimonials/'
    | '/admin/typography/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/clients'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/reels'
    | '/sitemap.xml'
    | '/weather'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/videos/$id'
    | '/photos'
    | '/services'
    | '/videos'
    | '/admin/events'
    | '/admin/galleries'
    | '/admin/inbox'
    | '/admin/media'
    | '/admin/places'
    | '/admin/reels'
    | '/admin/studio'
    | '/admin/ticker'
    | '/api/media/$'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/clients/$id'
    | '/admin/faqs/$id'
    | '/admin/gallery/$id'
    | '/admin/leads/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/team/$id'
    | '/admin/testimonials/$id'
    | '/admin/typography/settings'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/leads'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/services'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/typography'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/business'
    | '/clients'
    | '/contact'
    | '/faq'
    | '/photos'
    | '/portfolio'
    | '/pricing'
    | '/reels'
    | '/services'
    | '/sitemap.xml'
    | '/videos'
    | '/weather'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/businesses/$slug'
    | '/galleries/$slug'
    | '/photos/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/videos/$id'
    | '/photos/'
    | '/services/'
    | '/videos/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/galleries'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/places'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/reels'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/studio'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/ticker'
    | '/_authenticated/admin/typography'
    | '/api/media/$'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/faqs/$id'
    | '/_authenticated/admin/gallery/$id'
    | '/_authenticated/admin/leads/$id'
    | '/_authenticated/admin/portfolio/$id'
    | '/_authenticated/admin/pricing/$id'
    | '/_authenticated/admin/services/$id'
    | '/_authenticated/admin/team/$id'
    | '/_authenticated/admin/testimonials/$id'
    | '/_authenticated/admin/typography/settings'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/faqs/'
    | '/_authenticated/admin/gallery/'
    | '/_authenticated/admin/leads/'
    | '/_authenticated/admin/portfolio/'
    | '/_authenticated/admin/pricing/'
    | '/_authenticated/admin/services/'
    | '/_authenticated/admin/team/'
    | '/_authenticated/admin/testimonials/'
    | '/_authenticated/admin/typography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PhotosRoute: typeof PhotosRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  ReelsRoute: typeof ReelsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRouteWithChildren
  WeatherRoute: typeof WeatherRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  GalleriesSlugRoute: typeof GalleriesSlugRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/photos/': {
      id: '/photos/'
      path: '/'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/photos/$id': {
      id: '/photos/$id'
      path: '/$id'
      fullPath: '/photos/$id'
      preLoaderRoute: typeof PhotosIdRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/galleries/$slug': {
      id: '/galleries/$slug'
      path: '/galleries/$slug'
      fullPath: '/galleries/$slug'
      preLoaderRoute: typeof GalleriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/typography': {
      id: '/_authenticated/admin/typography'
      path: '/typography'
      fullPath: '/admin/typography'
      preLoaderRoute: typeof AuthenticatedAdminTypographyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticker': {
      id: '/_authenticated/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AuthenticatedAdminTickerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/studio': {
      id: '/_authenticated/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AuthenticatedAdminStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reels': {
      id: '/_authenticated/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AuthenticatedAdminReelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/places': {
      id: '/_authenticated/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AuthenticatedAdminPlacesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galleries': {
      id: '/_authenticated/admin/galleries'
      path: '/galleries'
      fullPath: '/admin/galleries'
      preLoaderRoute: typeof AuthenticatedAdminGalleriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/typography/': {
      id: '/_authenticated/admin/typography/'
      path: '/'
      fullPath: '/admin/typography/'
      preLoaderRoute: typeof AuthenticatedAdminTypographyIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTypographyRoute
    }
    '/_authenticated/admin/testimonials/': {
      id: '/_authenticated/admin/testimonials/'
      path: '/'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTestimonialsRoute
    }
    '/_authenticated/admin/team/': {
      id: '/_authenticated/admin/team/'
      path: '/'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AuthenticatedAdminTeamIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTeamRoute
    }
    '/_authenticated/admin/services/': {
      id: '/_authenticated/admin/services/'
      path: '/'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AuthenticatedAdminServicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminServicesRoute
    }
    '/_authenticated/admin/pricing/': {
      id: '/_authenticated/admin/pricing/'
      path: '/'
      fullPath: '/admin/pricing/'
      preLoaderRoute: typeof AuthenticatedAdminPricingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPricingRoute
    }
    '/_authenticated/admin/portfolio/': {
      id: '/_authenticated/admin/portfolio/'
      path: '/'
      fullPath: '/admin/portfolio/'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPortfolioRoute
    }
    '/_authenticated/admin/leads/': {
      id: '/_authenticated/admin/leads/'
      path: '/'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/gallery/': {
      id: '/_authenticated/admin/gallery/'
      path: '/'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AuthenticatedAdminGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminGalleryRoute
    }
    '/_authenticated/admin/faqs/': {
      id: '/_authenticated/admin/faqs/'
      path: '/'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AuthenticatedAdminFaqsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminFaqsRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/typography/settings': {
      id: '/_authenticated/admin/typography/settings'
      path: '/settings'
      fullPath: '/admin/typography/settings'
      preLoaderRoute: typeof AuthenticatedAdminTypographySettingsRouteImport
      parentRoute: typeof AuthenticatedAdminTypographyRoute
    }
    '/_authenticated/admin/testimonials/$id': {
      id: '/_authenticated/admin/testimonials/$id'
      path: '/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsIdRouteImport
      parentRoute: typeof AuthenticatedAdminTestimonialsRoute
    }
    '/_authenticated/admin/team/$id': {
      id: '/_authenticated/admin/team/$id'
      path: '/$id'
      fullPath: '/admin/team/$id'
      preLoaderRoute: typeof AuthenticatedAdminTeamIdRouteImport
      parentRoute: typeof AuthenticatedAdminTeamRoute
    }
    '/_authenticated/admin/services/$id': {
      id: '/_authenticated/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AuthenticatedAdminServicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminServicesRoute
    }
    '/_authenticated/admin/pricing/$id': {
      id: '/_authenticated/admin/pricing/$id'
      path: '/$id'
      fullPath: '/admin/pricing/$id'
      preLoaderRoute: typeof AuthenticatedAdminPricingIdRouteImport
      parentRoute: typeof AuthenticatedAdminPricingRoute
    }
    '/_authenticated/admin/portfolio/$id': {
      id: '/_authenticated/admin/portfolio/$id'
      path: '/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedAdminPortfolioRoute
    }
    '/_authenticated/admin/leads/$id': {
      id: '/_authenticated/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/gallery/$id': {
      id: '/_authenticated/admin/gallery/$id'
      path: '/$id'
      fullPath: '/admin/gallery/$id'
      preLoaderRoute: typeof AuthenticatedAdminGalleryIdRouteImport
      parentRoute: typeof AuthenticatedAdminGalleryRoute
    }
    '/_authenticated/admin/faqs/$id': {
      id: '/_authenticated/admin/faqs/$id'
      path: '/$id'
      fullPath: '/admin/faqs/$id'
      preLoaderRoute: typeof AuthenticatedAdminFaqsIdRouteImport
      parentRoute: typeof AuthenticatedAdminFaqsRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
  }
}

interface AuthenticatedAdminBlogRouteChildren {
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminBlogRouteChildren: AuthenticatedAdminBlogRouteChildren =
  {
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  }

const AuthenticatedAdminBlogRouteWithChildren =
  AuthenticatedAdminBlogRoute._addFileChildren(
    AuthenticatedAdminBlogRouteChildren,
  )

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminFaqsRouteChildren {
  AuthenticatedAdminFaqsIdRoute: typeof AuthenticatedAdminFaqsIdRoute
  AuthenticatedAdminFaqsIndexRoute: typeof AuthenticatedAdminFaqsIndexRoute
}

const AuthenticatedAdminFaqsRouteChildren: AuthenticatedAdminFaqsRouteChildren =
  {
    AuthenticatedAdminFaqsIdRoute: AuthenticatedAdminFaqsIdRoute,
    AuthenticatedAdminFaqsIndexRoute: AuthenticatedAdminFaqsIndexRoute,
  }

const AuthenticatedAdminFaqsRouteWithChildren =
  AuthenticatedAdminFaqsRoute._addFileChildren(
    AuthenticatedAdminFaqsRouteChildren,
  )

interface AuthenticatedAdminGalleryRouteChildren {
  AuthenticatedAdminGalleryIdRoute: typeof AuthenticatedAdminGalleryIdRoute
  AuthenticatedAdminGalleryIndexRoute: typeof AuthenticatedAdminGalleryIndexRoute
}

const AuthenticatedAdminGalleryRouteChildren: AuthenticatedAdminGalleryRouteChildren =
  {
    AuthenticatedAdminGalleryIdRoute: AuthenticatedAdminGalleryIdRoute,
    AuthenticatedAdminGalleryIndexRoute: AuthenticatedAdminGalleryIndexRoute,
  }

const AuthenticatedAdminGalleryRouteWithChildren =
  AuthenticatedAdminGalleryRoute._addFileChildren(
    AuthenticatedAdminGalleryRouteChildren,
  )

interface AuthenticatedAdminLeadsRouteChildren {
  AuthenticatedAdminLeadsIdRoute: typeof AuthenticatedAdminLeadsIdRoute
  AuthenticatedAdminLeadsIndexRoute: typeof AuthenticatedAdminLeadsIndexRoute
}

const AuthenticatedAdminLeadsRouteChildren: AuthenticatedAdminLeadsRouteChildren =
  {
    AuthenticatedAdminLeadsIdRoute: AuthenticatedAdminLeadsIdRoute,
    AuthenticatedAdminLeadsIndexRoute: AuthenticatedAdminLeadsIndexRoute,
  }

const AuthenticatedAdminLeadsRouteWithChildren =
  AuthenticatedAdminLeadsRoute._addFileChildren(
    AuthenticatedAdminLeadsRouteChildren,
  )

interface AuthenticatedAdminPortfolioRouteChildren {
  AuthenticatedAdminPortfolioIdRoute: typeof AuthenticatedAdminPortfolioIdRoute
  AuthenticatedAdminPortfolioIndexRoute: typeof AuthenticatedAdminPortfolioIndexRoute
}

const AuthenticatedAdminPortfolioRouteChildren: AuthenticatedAdminPortfolioRouteChildren =
  {
    AuthenticatedAdminPortfolioIdRoute: AuthenticatedAdminPortfolioIdRoute,
    AuthenticatedAdminPortfolioIndexRoute:
      AuthenticatedAdminPortfolioIndexRoute,
  }

const AuthenticatedAdminPortfolioRouteWithChildren =
  AuthenticatedAdminPortfolioRoute._addFileChildren(
    AuthenticatedAdminPortfolioRouteChildren,
  )

interface AuthenticatedAdminPricingRouteChildren {
  AuthenticatedAdminPricingIdRoute: typeof AuthenticatedAdminPricingIdRoute
  AuthenticatedAdminPricingIndexRoute: typeof AuthenticatedAdminPricingIndexRoute
}

const AuthenticatedAdminPricingRouteChildren: AuthenticatedAdminPricingRouteChildren =
  {
    AuthenticatedAdminPricingIdRoute: AuthenticatedAdminPricingIdRoute,
    AuthenticatedAdminPricingIndexRoute: AuthenticatedAdminPricingIndexRoute,
  }

const AuthenticatedAdminPricingRouteWithChildren =
  AuthenticatedAdminPricingRoute._addFileChildren(
    AuthenticatedAdminPricingRouteChildren,
  )

interface AuthenticatedAdminServicesRouteChildren {
  AuthenticatedAdminServicesIdRoute: typeof AuthenticatedAdminServicesIdRoute
  AuthenticatedAdminServicesIndexRoute: typeof AuthenticatedAdminServicesIndexRoute
}

const AuthenticatedAdminServicesRouteChildren: AuthenticatedAdminServicesRouteChildren =
  {
    AuthenticatedAdminServicesIdRoute: AuthenticatedAdminServicesIdRoute,
    AuthenticatedAdminServicesIndexRoute: AuthenticatedAdminServicesIndexRoute,
  }

const AuthenticatedAdminServicesRouteWithChildren =
  AuthenticatedAdminServicesRoute._addFileChildren(
    AuthenticatedAdminServicesRouteChildren,
  )

interface AuthenticatedAdminTeamRouteChildren {
  AuthenticatedAdminTeamIdRoute: typeof AuthenticatedAdminTeamIdRoute
  AuthenticatedAdminTeamIndexRoute: typeof AuthenticatedAdminTeamIndexRoute
}

const AuthenticatedAdminTeamRouteChildren: AuthenticatedAdminTeamRouteChildren =
  {
    AuthenticatedAdminTeamIdRoute: AuthenticatedAdminTeamIdRoute,
    AuthenticatedAdminTeamIndexRoute: AuthenticatedAdminTeamIndexRoute,
  }

const AuthenticatedAdminTeamRouteWithChildren =
  AuthenticatedAdminTeamRoute._addFileChildren(
    AuthenticatedAdminTeamRouteChildren,
  )

interface AuthenticatedAdminTestimonialsRouteChildren {
  AuthenticatedAdminTestimonialsIdRoute: typeof AuthenticatedAdminTestimonialsIdRoute
  AuthenticatedAdminTestimonialsIndexRoute: typeof AuthenticatedAdminTestimonialsIndexRoute
}

const AuthenticatedAdminTestimonialsRouteChildren: AuthenticatedAdminTestimonialsRouteChildren =
  {
    AuthenticatedAdminTestimonialsIdRoute:
      AuthenticatedAdminTestimonialsIdRoute,
    AuthenticatedAdminTestimonialsIndexRoute:
      AuthenticatedAdminTestimonialsIndexRoute,
  }

const AuthenticatedAdminTestimonialsRouteWithChildren =
  AuthenticatedAdminTestimonialsRoute._addFileChildren(
    AuthenticatedAdminTestimonialsRouteChildren,
  )

interface AuthenticatedAdminTypographyRouteChildren {
  AuthenticatedAdminTypographySettingsRoute: typeof AuthenticatedAdminTypographySettingsRoute
  AuthenticatedAdminTypographyIndexRoute: typeof AuthenticatedAdminTypographyIndexRoute
}

const AuthenticatedAdminTypographyRouteChildren: AuthenticatedAdminTypographyRouteChildren =
  {
    AuthenticatedAdminTypographySettingsRoute:
      AuthenticatedAdminTypographySettingsRoute,
    AuthenticatedAdminTypographyIndexRoute:
      AuthenticatedAdminTypographyIndexRoute,
  }

const AuthenticatedAdminTypographyRouteWithChildren =
  AuthenticatedAdminTypographyRoute._addFileChildren(
    AuthenticatedAdminTypographyRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRouteWithChildren
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRouteWithChildren
  AuthenticatedAdminGalleriesRoute: typeof AuthenticatedAdminGalleriesRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRouteWithChildren
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPlacesRoute: typeof AuthenticatedAdminPlacesRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRouteWithChildren
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRouteWithChildren
  AuthenticatedAdminReelsRoute: typeof AuthenticatedAdminReelsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRouteWithChildren
  AuthenticatedAdminStudioRoute: typeof AuthenticatedAdminStudioRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRouteWithChildren
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRouteWithChildren
  AuthenticatedAdminTickerRoute: typeof AuthenticatedAdminTickerRoute
  AuthenticatedAdminTypographyRoute: typeof AuthenticatedAdminTypographyRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRouteWithChildren,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRouteWithChildren,
  AuthenticatedAdminGalleriesRoute: AuthenticatedAdminGalleriesRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRouteWithChildren,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPlacesRoute: AuthenticatedAdminPlacesRoute,
  AuthenticatedAdminPortfolioRoute:
    AuthenticatedAdminPortfolioRouteWithChildren,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRouteWithChildren,
  AuthenticatedAdminReelsRoute: AuthenticatedAdminReelsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRouteWithChildren,
  AuthenticatedAdminStudioRoute: AuthenticatedAdminStudioRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRouteWithChildren,
  AuthenticatedAdminTestimonialsRoute:
    AuthenticatedAdminTestimonialsRouteWithChildren,
  AuthenticatedAdminTickerRoute: AuthenticatedAdminTickerRoute,
  AuthenticatedAdminTypographyRoute:
    AuthenticatedAdminTypographyRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PhotosRouteChildren {
  PhotosIdRoute: typeof PhotosIdRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
}

const PhotosRouteChildren: PhotosRouteChildren = {
  PhotosIdRoute: PhotosIdRoute,
  PhotosIndexRoute: PhotosIndexRoute,
}

const PhotosRouteWithChildren =
  PhotosRoute._addFileChildren(PhotosRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PhotosRoute: PhotosRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  ReelsRoute: ReelsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRouteWithChildren,
  WeatherRoute: WeatherRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  GalleriesSlugRoute: GalleriesSlugRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
